<?php

/**
 * Implements hook_user_login().
 */
/**
 * Implements hook_user_login().
 */
function welcome_block_user_login(\Drupal\user\UserInterface $account) {
  // Ignore password reset.
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name !== 'user.reset.login') {
    // Do not interfere if a destination was already set.
    $current_request = \Drupal::service('request_stack')->getCurrentRequest();
    if (!$current_request->query->get('destination')) {
      $current_request->query->set('destination', '/custom-welcome-page');
    }
  }
}
